---

- include: 0_stat_vsd_settings.yml
  when: groups['stat']|length > 0

- include: 1_enable_stat_nginx.yml 
  when: groups['stat']|length > 0

- include: 2_util_install.yml
  when: groups['util']|length > 0

- include: 3_create_proxy_user.yml
  when: groups['util']|length > 0

- include: 4_vsc_certs_create.yml 
  when: groups['util']|length > 0
